### ISSUE TITLE
Where to (logically) store specifications?

### ISSUE THREAD

**Issue by dsentker** [frankdejonge/doctrine-query-specification#2]
Awesome package, thank you for your work. In which namespace should one store these specification classes? It would be wrong in the `/src/Entity` folder because the entities only represent the database, not a filter for database requests. It would be more logical in the `/src/Repository` direcotry, but a specification has a different task than a repository. It only remains (IMHO) a separate directory (eg. `/src/Specification`), or what do you think? It would be nice if the README can clarify that so that all developers who use this package have a uniform folder structure.

**Comment by Brammm** [comment]
If I may weigh in here: I've been following the advice from [Eric Evans' blue book](http://domainlanguage.com/ddd/blue-book/) and @matthiasnoback ([His Layers article that sketches the same](https://matthiasnoback.nl/2017/08/layers-ports-and-adapters-part-2-layers/)) and it's worked really well for me over the last couple of years. In summary:

Separate your code in three top level domains: 

- Application
- Domain
- Infrastructure

Infrastructure contains all the code that isn't necessarily tied to your business logic. It's things like controllers, authentication, middleware, specific interface implementations...

Domain is the heart of your business logic. I find it makes more sense to group things in this namespace per [aggregate](https://martinfowler.com/bliki/DDD_Aggregate.html) root. E.g `src/Domain/User/User`, `src/Domain/User/UserRepository`, ` src/Domain/User/UserId`, ` src/Domain/Blog/Blog`, `src/Domain/Blog/Comment`  (comment lives under the Blog namespace as it's part of the aggregate). 

The last layer, the Application layer, according to the blue book, "defines the jobs the software is supposed to do and directs the expressive domain objects to work out problems". It contains things like commands and command handlers (although this can be debated and I've heard @ocramius for example express a different opinion on this). I let the subnamespaces of the the Application namespace mimic those of the Domain namespace. So for example `src/Application/User/RegisterUser`, ` src/Application/Blog/PublishArticle`... 

Following the logic above, Specifications would live in the Application namespace, in the namespace of the aggregate root it relates to, e.g. `src/Application/Blog/FrontPageArticles`. If these namespaces become too cluttered, you could still split them up further into `Specification`, `Command` ...

Lastly, some great advice from the React docs that apply here as well: [Don't overthink it](https://reactjs.org/docs/faq-structure.html#dont-overthink-it).

**Comment by frankdejonge** [comment]
I place these along side the doctrine repository implementations. The specifications are pretty doctrine specific. You could create more elaborate specification patterns that work for collections as well as databases, but for this package it's tailored towards just querying entities.

**Comment by Brammm** [comment]
I got so wrapped up in my own "this works for me" that I didn't consider
the specific implementation here. You're right, they make more sense to sit
next to the repository implementation.
