### ISSUE TITLE
Interface QueryConstraint requires nullable object to be returned, making `isNotNull` checks impossible.

### ISSUE THREAD

**Issue by Brammm** [frankdejonge/doctrine-query-specification#7]
The QueryConstraint interface requires that the `asQueryConstraint` method either returns `null` or an object. The documentation shows examples like 

```
    public function asQueryConstraint(QueryBuilder $builder, $rootAlias): Composite
    {
        $expr = $builder->expr();
        
        return $expr->eq("{$rootAlias}.published", true);
    }
```
(besides the docs being wrong here, the typehint should be ?object as far as I understand)

this makes the following example impossible:

```
    public function asQueryConstraint(QueryBuilder $builder, $rootAlias): Composite
    {
        $expr = $builder->expr();
        
        return $expr->isNotNull("{$rootAlias}.date_published");
    }
```

as `isNotNull` will simply return a string, not an object.

Are my assumptions correct? If so, I'll gladly submit a PR to fix the interface.

**Comment by frankdejonge** [comment]
Hi @Brammm this issue is from a while back, but I've pushed a test issue showing how to use isNotNull.
